server:
  port: 7080  # 项目端口
  basePath: "/readygo"  # 项目基础路径

database:
  dsn: "root:root@tcp(127.0.0.1:3306)/readygo?charset=utf8&parseTime=true&loc=Local"
  driverName: "mysql"
  dialect: "mysql"
  maxOpenConns: 50
  maxIdleConns: 50
  connMaxLifetimeSecond: 600
  slowSQLMillis: 0

redis:
  addr: "127.0.0.1:6379"
  password: ""
  poolSize: 10
  minIdleConns: 10

jwt:
  tokenName: "READYGOTOKEN" # jwt token名称
  secret: "JWTSecret" # jwt加密密钥
  timeout: 3600 # token过期时间