basePath: /
host: 127.0.0.1:8080
info:
  contact: {}
  description: This is a sample server Petstore server.
  title: Swagger Example API
  version: "1.0"
paths:
  /test/{id}:
    get:
      description: 接口详细描述信息
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: name
        in: query
        name: name
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 接口概要说明
      tags:
      - 登陆   //swagger API分类标签
      - 同一个tag为一组
swagger: "2.0"
